name: flutter_device_apps_platform_interface
description: Platform-agnostic API contract for flutter_device_apps (federated).
version: 0.1.2
repository: https://github.com/okmsbun/flutter_device_apps
issue_tracker: https://github.com/okmsbun/flutter_device_apps/issues
topics:
  - flutter
  - plugin
  - federated-plugin
  - android

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  lints: ^6.0.0
